info:
  name: Get aggregated downloads from all configured clients
  type: http
  seq: 1

http:
  method: GET
  url: "{{baseUrl}}/downloads"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: 200 Response
    description: Download status with all items
    request:
      url: "{{baseUrl}}/downloads"
      method: GET
    response:
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "total_speed": 0,
            "queue_size": 0,
            "items": [
              {
                "name": "",
                "progress": 0,
                "speed": 0,
                "eta": "",
                "status": "",
                "size": 0,
                "downloaded": 0,
                "client_name": "",
                "client_type": ""
              }
            ]
          }
  - name: 500 Response
    description: Internal server error
    request:
      url: "{{baseUrl}}/downloads"
      method: GET
    response:
      statusText: Internal Server Error
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "error": "",
            "status": 0
          }
